### ISSUE TITLE
Fatal errors and breaking site with new install

### ISSUE THREAD

**Issue by adrianbj** [teppokoivula/ProcessChangelog#8]
I just tried to install this on a site and received these errors. Checked on another site and the same thing. Pretty critical since the only way to get back into your site is to remove the module's folder.

Looks like it would probably be fine as an update to an old version of ProcessChangeLog, but not as a new install.

```
Fatal error: Exception: Couldn't update database schema to version 2 (in /Sites/pwnew/site/modules/ProcessChangelog/ProcessChangelogHooks.module line 427) #0 /Sites/pwnew/site/modules/ProcessChangelog/ProcessChangelogHooks.module(164): ProcessChangelogHooks->updateDatabaseSchema() #1 /Sites/pwnew/wire/core/Modules.php(441): ProcessChangelogHooks->init() #2 /Sites/pwnew/wire/core/Modules.php(358): Modules->initModule(Object(ProcessChangelogHooks)) #3 /Sites/pwnew/wire/core/ProcessWire.php(305): Modules->triggerInit() #4 [internal function]: ProcessWire->___init() #5 /Sites/pwnew/wire/core/Wire.php(383): call_user_func_array(Array, Array) #6 /Sites/pwnew/wire/core/Wire.php(321): Wire->runHooks('init', Array) #7 /Sites/pwnew/wire/core/ProcessWire.php(347): Wire->__call('init', Array) #8 /Sites/pwnew/wire/core/ProcessWire.php(288): ProcessWire->__call('init', Array) #9 /Sites/pwnew/wire/core/Proce in /Sites/pwnew/index.php on line 252
```

After that, reloading the page results in the following, although this is not surprising given the error from the first attempt.

```
Fatal error: Exception: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'templates_id' (in /Sites/pwnew/wire/core/WireDatabasePDO.php line 191) #0 /Sites/pwnew/wire/core/WireDatabasePDO.php(191): PDO->exec('ALTER TABLE pro...') #1 /Sites/pwnew/site/modules/ProcessChangelog/ProcessChangelogHooks.module(422): WireDatabasePDO->exec('ALTER TABLE pro...') #2 /Sites/pwnew/site/modules/ProcessChangelog/ProcessChangelogHooks.module(164): ProcessChangelogHooks->updateDatabaseSchema() #3 /Sites/pwnew/wire/core/Modules.php(441): ProcessChangelogHooks->init() #4 /Sites/pwnew/wire/core/Modules.php(358): Modules->initModule(Object(ProcessChangelogHooks)) #5 /Sites/pwnew/wire/core/ProcessWire.php(305): Modules->triggerInit() #6 [internal function]: ProcessWire->___init() #7 /Sites/pwnew/wire/core/Wire.php(383): call_user_func_array(Array, Array) #8 /Sites/pwnew/wire/core/Wire.php(321): Wire->runHooks(' in /Sites/pwnew/index.php on line 252
```

**Comment by eladnova** [comment]
Dup of this?
https://github.com/teppokoivula/ProcessChangelog/issues/7

**Comment by adrianbj** [comment]
Yeah sorry I guess it is - I was thrown by the initial "Couldn't update database schema to version 2" message.

**Comment by eladnova** [comment]
No worries. I was really just flagging that you're not the only one to experience this.
Was quicker on the iPad to lazy type the shorter reply :)

Hoping this is fixed soon. Such a great Module.

**Comment by teppokoivula** [comment]
Fixed these issues. Longer description in #7 :)
